apiVersion: security.istio.io/v1beta1
kind: PeerAuthentication
metadata:
  name: kiali-permissive
  namespace: istio-system
spec:
  selector:
    matchLabels:
      app: kiali
  mtls:
    mode: PERMISSIVE