apiVersion: security.istio.io/v1beta1
kind: PeerAuthentication
metadata:
  name: jaeger-permissive
  namespace: istio-system  # namespace donde esta Jaeger
spec:
  selector:
    matchLabels:
      app: jaeger
  mtls:
    mode: PERMISSIVE