apiVersion: security.istio.io/v1beta1
kind: PeerAuthentication
metadata:
  name: grafana-permissive
  namespace: istio-system
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: grafana
  mtls:
    mode: PERMISSIVE