apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: ms-appointments
  namespace: ordendev
spec:
  host: ms-appointments
  subsets:
    - name: v1
      labels:
        version: v1
