apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: ms-patients
  namespace: ordendev
spec:
  host: ms-patients
  subsets:
    - name: v1
      labels:
        version: v1
