apiVersion: networking.istio.io/v1beta1
kind: ServiceEntry
metadata:
  name: postgres-db
spec:
  hosts:
  - database-1.cd36cemukdvq.us-east-1.rds.amazonaws.com
  location: MESH_EXTERNAL
  ports:
  - number: 5432
    name: tcp-postgres
    protocol: TCP
  resolution: DNS
