apiVersion: v1
kind: Service
metadata:
  name: ms-patients
  namespace: ordendev
  labels:
    app: ms-patients
spec:
  type: ClusterIP
  selector:
    app: ms-patients
  ports:
    - name: http
      port: 8080
      targetPort: 3000
