apiVersion: constraints.gatekeeper.sh/v1beta1
kind: K8sNoNodePort   # Debe coincidir con el kind del Template
metadata:
  name: forbid-nodeport
spec:
  match:
    kinds:
      - apiGroups: [""]       # Service esta en el grupo core, por eso ""
        kinds: ["Service"]
