apiVersion: constraints.gatekeeper.sh/v1beta1
kind: K8sMaxMemoryRequest
metadata:
  name: max-memory-request-512mi
spec:
  match:
    kinds:
      - apiGroups: [""]
        kinds: ["Pod"]
      - apiGroups: ["apps"]
        kinds: ["Deployment", "StatefulSet", "DaemonSet", "ReplicaSet"]
  parameters:
    maxMemory: "512Mi"
