apiVersion: templates.gatekeeper.sh/v1
kind: ConstraintTemplate
metadata:
  name: k8snonodeport
spec:
  crd:
    spec:
      names:
        kind: K8sNoNodePort
  targets:
    - target: admission.k8s.gatekeeper.sh
      rego: |
        package k8snonodeport

        violation[{"msg": msg}] {
          input.review.object.spec.type == "NodePort"
          msg := sprintf("No se permite crear Service de tipo NodePort: %s", [input.review.object.metadata.name])
        }
